function A1dot = A1dotfunc(a,dq3,dq4,dq5,dq6,dq7,dq8,dq9,l1,l2,q3,q4,q5,q6,q7,q8,q9)
%A1dotfunc
%    A1dot = A1dotfunc(A,DQ3,DQ4,DQ5,DQ6,DQ7,DQ8,DQ9,L1,L2,Q3,Q4,Q5,Q6,Q7,Q8,Q9)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Jul-2022 10:20:12

t2 = sqrt(3.0);
t3 = pi./3.0;
t4 = pi./6.0;
t5 = q3+t3;
t6 = q3+t4;
A1dot = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,a.*dq3.*t2.*cos(t6).*(-1.0./3.0),a.*dq3.*t2.*sin(t6).*(-1.0./3.0),(a.*dq3.*t2.*sin(t5))./3.0,a.*dq3.*t2.*cos(t5).*(-1.0./3.0),a.*dq3.*t2.*sin(q3).*(-1.0./3.0),(a.*dq3.*t2.*cos(q3))./3.0,-dq4.*l1.*cos(q4),-dq4.*l1.*sin(q4),0.0,0.0,0.0,0.0,-dq5.*l2.*cos(q5),-dq5.*l2.*sin(q5),0.0,0.0,0.0,0.0,0.0,0.0,-dq6.*l1.*cos(q6),-dq6.*l1.*sin(q6),0.0,0.0,0.0,0.0,-dq7.*l2.*cos(q7),-dq7.*l2.*sin(q7),0.0,0.0,0.0,0.0,0.0,0.0,-dq8.*l1.*cos(q8),-dq8.*l1.*sin(q8),0.0,0.0,0.0,0.0,-dq9.*l2.*cos(q9),-dq9.*l2.*sin(q9)],[6,9]);
